<a href="https://colab.research.google.com/github/Archangel212/psgan-pytorch/blob/master/psgan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git config --global user.name "Archangel212"
!git config --global user.email "michaeldavidbaskoro@gmail.com" 
!git clone -b zero_global_dimension https://github.com/Archangel212/psgan-pytorch

Cloning into 'psgan-pytorch'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1284 (delta 0), reused 3 (delta 0), pack-reused 1277
Receiving objects: 100% (1284/1284), 1.62 GiB | 42.96 MiB/s, done.
Resolving deltas: 100% (51/51), done.
Checking out files: 100% (1324/1324), done.


In [2]:
import datetime
import pytz

utc_now = pytz.utc.localize(datetime.datetime.now())
wib_now = utc_now.astimezone(pytz.timezone("Asia/Jakarta"))
print(wib_now.strftime("%A_%d-%B-%Y_%H:%M:%S"), utc_now.strftime("%A_%d-%B-%Y_%H:%M:%S"))

Saturday_12-December-2020_07:10:29 Saturday_12-December-2020_00:10:29


In [3]:
import matplotlib.pyplot as plt
import PIL
import torchvision
import torch
import os
from shutil import copyfile
from pathlib import Path

In [4]:
batik_dataset_name="Batik_41_500by500_Single_image"
experiment_name="single_honeycomb_cardinal_dimensionality"

#hyperparameters
not_cuda	=	0
manualSeed	=	452
nfc	=	64
ker_size	=	3
num_layer	=	5
padd_size	=	0
nc_im	=	3
noise_amp	=	0.1
min_size	=	25
max_size	=	250
train_depth	=	3 #num of concurrently trained stages
start_scale	=	0
niter	=	2000
gamma	=	0.1
lr_g	=	0.0005
lr_d	=	0.0005
beta1	=	0.5
Gsteps	=	3
Dsteps	=	3
lambda_grad	=	0.1
alpha	=	10
lrelu_alpha	=	0.05
batch_norm	=	0
lr_scale	=	0.1
train_stages	=	6
fine_tune	=	0
noise_amp_init	=	0.1






In [5]:
%cd /content/psgan-pytorch


/content/psgan-pytorch


In [7]:
!python train.py --dataset batik_dataset/$batik_dataset_name --save_dir ./log/$batik_dataset_name/$experiment_name --tqdm_notebook True
# !python random_samples.py --input_name $sample_name --mode random_samples --gen_start_scale 

Streaming output truncated to the last 5000 lines.

[#8335]train epoch dloss: 0.05677, gloss: 5.39681

[#8336]train epoch dloss: 0.03300, gloss: 5.76045

[#8337]train epoch dloss: 0.05338, gloss: 5.43989

[#8338]train epoch dloss: 0.02102, gloss: 5.80165

[#8339]train epoch dloss: 0.17135, gloss: 11.30545

[#8340]train epoch dloss: 0.14358, gloss: 11.75122

[#8341]train epoch dloss: 0.93991, gloss: 5.15225

[#8342]train epoch dloss: 0.04962, gloss: 4.59096

[#8343]train epoch dloss: 0.68700, gloss: 15.39680

[#8344]train epoch dloss: 0.51372, gloss: 8.72976

[#8345]train epoch dloss: 0.00618, gloss: 6.49700

[#8346]train epoch dloss: 0.18786, gloss: 8.69096

[#8347]train epoch dloss: 0.11735, gloss: 14.36687

[#8348]train epoch dloss: 0.24217, gloss: 12.04400

[#8349]train epoch dloss: 0.04346, gloss: 8.12206

[#8350]train epoch dloss: 0.00709, gloss: 8.04771

[#8351]train epoch dloss: 0.02022, gloss: 6.14305

[#8352]train epoch dloss: 0.05307, gloss: 6.77184

[#8353]train epoch dloss:

In [ ]:
# last_modified = sorted(Path(os.path.join("TrainedModels/",sample_name[:-4])).iterdir(), key=os.path.getmtime)[-1]
# last_modified = os.path.join("/content/ConSinGAN/", last_modified)

# !python evaluate_model.py --gpu 0 --model_dir $last_modified  --num_samples 50

In [ ]:
import torchvision.utils as vutils
import matplotlib.pyplot as plt
import os
import numpy as np


#@title show random samples output in grid
def make_dataloader():
  """return dataloader and its associated labels"""
  device = "gpu" if torch.cuda.is_available() else "cpu"
  # output_path = "/content/ConSinGAN/TrainedModels/Batik_156/2020_11_07_15_20_22_generation_train_depth_3_lr_scale_0.1_act_lrelu_0.05/Evaluation/random_samples"
  # output_path = "/content/ConSinGAN/TrainedModels/Batik_156/2020_11_09_17_52_26_generation_train_depth_3_lr_scale_0.2_act_lrelu_0.05/Evaluation/random_samples"
  # output_path = "/content/ConSinGAN/TrainedModels/Batik_156/2020_11_09_19_36_59_generation_train_depth_3_lr_scale_0.3_act_lrelu_0.05/Evaluation/random_samples"
  # output_path = "/content/ConSinGAN/TrainedModels/Batik_156/2020_11_10_07_30_18_generation_train_depth_2_lr_scale_0.3_act_lrelu_0.05/Evaluation/random_samples"
  output_path = os.path.join(last_modified, "Evaluation/random_samples")
  os.chdir(output_path)
  lsdir = [i for i in os.listdir(".")]
    
  imgs_tensor = []
  for img in lsdir:
    img_rgb = PIL.Image.open(img).convert("RGB")
    imgs_tensor.append(np.array(img_rgb))
  
  imgs_tensor = np.moveaxis(np.array(imgs_tensor), -1,1)
  print(np.array(imgs_tensor).shape)
  tensors = torch.Tensor(imgs_tensor)
  tensors = torch.unsqueeze(tensors,0)
  dataloader = torch.utils.data.DataLoader(tensors) 
  return dataloader

def make_grid(image_loader, title):
  image_loader = next(iter(image_loader))
  print(image_loader.size())

  plt.figure(figsize=(30,30))
  plt.axis("off")
  plt.title(title)
  print(np.transpose(vutils.make_grid(image_loader[0], padding=10, nrow=2), (1,2,0)).shape)
  plt.imshow(np.transpose(vutils.make_grid(image_loader[0], padding=10, nrow=10, normalize=True), (1,2,0)))

# dataloader = make_dataloader()
# make_grid(dataloader, sample_name)

In [9]:
# commit_msg = "Training and generating random {} scale {} and act_lrelu {} \
#  train_depth 4 and 5 ".format(sample_name, lr_scale, lrelu_alpha)

# !echo $commit_msg
!git config --global user.name "Archangel212"
!git config --global user.email "michaeldavidbaskoro@gmail.com" 
!git add --all
!git commit -m "Training ${batik_dataset_name} with ${experiment_name}"
# # !git commit -m "Training $sample_name with alpha 10"

!git remote set-url origin https://Archangel212:fibonacci382618@github.com/Archangel212/psgan-pytorch.git
!git push --set-upstream origin zero_global_dimension

On branch zero_global_dimension
Your branch is ahead of 'origin/zero_global_dimension' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Counting objects: 32, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (31/31), done.
Writing objects: 100% (32/32), 70.59 MiB | 9.49 MiB/s, done.
Total 32 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/Archangel212/psgan-pytorch.git
   dd1ed6e..04f2e7e  zero_global_dimension -> zero_global_dimension
Branch 'zero_global_dimension' set up to track remote branch 'zero_global_dimension' from 'origin'.


In [1]:
import torch.nn as nn
import torch.functional as F
import torch

In [2]:
x = torch.Tensor([[0.0,0.1],
                  [0.0,0.1],
                  [0.0,0.1]])
input = x.shape[1]
output = 2

In [11]:
linear = nn.Linear(input, output)
print(linear.weight.requires_grad_(), linear.bias)
y = linear(x)

Parameter containing:
tensor([[-0.1188, -0.1536],
        [ 0.4164, -0.2437]], requires_grad=True) Parameter containing:
tensor([-0.6902,  0.6930], requires_grad=True)


tensor([[-0.7056,  0.6686],
        [-0.7056,  0.6686],
        [-0.7056,  0.6686]], grad_fn=<AddmmBackward>)

In [21]:
y = torch.matmul(x, linear.weight.T) + linear.bias
print(y)
b = torch.empty((1,2), requires_grad=False)
b.requires_grad_()

tensor([[-0.7056,  0.6686],
        [-0.7056,  0.6686],
        [-0.7056,  0.6686]], grad_fn=<AddBackward0>)


tensor([[3.4676e-35, 0.0000e+00]], requires_grad=True)

In [22]:
class Discriminator(nn.Module):
  inplace_flag = False
  def __init__(self, conv_channels=[3, 64, 128, 256, 512, 1], kernel_size=5, padding=1):
    super(Discriminator, self).__init__()
    """
        args:
            conv_channel: list of int
                the channel of convolution layer will be construct on this.

            kernel_size; int 
                the size of kernel. 
    """

    layers = []
    for ch_index in range(1, len(conv_channels)-1):
        layers.append(nn.Conv2d(in_channels=conv_channels[ch_index-1], out_channels=conv_channels[ch_index], kernel_size=kernel_size, stride=2, padding=padding))
        if ch_index != 1:
            layers.append(nn.BatchNorm2d(conv_channels[ch_index]))
        layers.append(nn.LeakyReLU(negative_slope=0.2, inplace=self.inplace_flag))

    layers.append(nn.Conv2d(in_channels=conv_channels[-2], out_channels=conv_channels[-1], kernel_size=kernel_size, stride=2, padding=padding))
    layers.append(nn.Sigmoid())
    self.discriminate = nn.Sequential(*layers)
    print(self.discriminate)

  def forward(self, x):
    x = self.discriminate(x)
    print(x.shape)



input = torch.rand((1,3,160,160))
D = Discriminator(padding=2)
D(input)

Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (1): LeakyReLU(negative_slope=0.2)
  (2): Conv2d(64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (4): LeakyReLU(negative_slope=0.2)
  (5): Conv2d(128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (6): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (7): LeakyReLU(negative_slope=0.2)
  (8): Conv2d(256, 512, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (9): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (10): LeakyReLU(negative_slope=0.2)
  (11): Conv2d(512, 1, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (12): Sigmoid()
)
torch.Size([1, 1, 5, 5])
